### ISSUE TITLE
[Instructions] Add Usage Instructions to README and KDE Store

### ISSUE THREAD

**Issue by bugzy** [naglfar/krunner-keepassxc#10]
How would you feel about adding/updating usage instructions to the git repo readme and to the KDE store? Below are instructions adapted from a comment by [nathanu](https://store.kde.org/u/nathanu) on the kde store page and your current description on the store

## Description:
This plugin let's you look up your KeepassXC entries and copy the passwords (and usernames as secondary action) to the system clipboard. It also comes with a small CLI tool to query that information manually.

### Requirements:
- Python 3.6 or higher
- KeepassXC installed and configured for Freedesktop.org Secret Service access (See below)

### Enable Secret Service in KeepassXC:
* Open KeepassXC client
* Go to: Database > Database Settings > Secret Service integration 
* Select "Expose entries under this group"
* Select the folder that you wish to make available through Secret Service (Select Root is you are not sure)
* Click OK
* Go to: Tools > Settings > Secret Service Integration 
* Check "Enable KeepassXC Freedesktop.org Secret Service integration"

### Usage Instructions:
* Launch KRunner. 
* Enter a search term from the title of the password entry you wish to obtain credentials for
* Mouse: can click on the entry you are looking for to copy the password to the clipboard.
* Mouse: can click on the icon to the right of the entry to copy the username. 
* Keyboard: navigate to the entry you want by using the arrow keys.
* Keyboard: Press enter to copy the password to the clipboard
* Keyboard: Press shift + enter, to copy the username to the clipboard.

### Other Information:
As this is a python application communicating with krunner through D-Bus it needs to be running constantly, for this purpose the install script will place the executable at ~/.local/bin/krunner-keepassxc (you can run this for the CLI) and place a systemd unit file at ~/.config/systemd/user/ to control it. If you're not using systemd a KDE autostart script will be created instead.

More info and alternative installation methods here https://github.com/naglfar/krunner-keepassxc/blob/master/README.md

**Comment by naglfar** [comment]
Updated readme and kde store description, thanks for the input
